vim.notify = require("notify")

vim.opt.tags=tags
-- syntax on
vim.opt.redrawtime = 10000
vim.opt.encoding = "UTF-8"
vim.opt.re = 0
vim.opt.splitright = true
-- vim.wo.noshowmatch = true
-- vim.opt.noshowmode = true
vim.opt.relativenumber = true
-- vim.opt.nohlsearch = true
vim.opt.hidden = true
vim.opt.tabstop = 2 
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.smarttab = true
vim.o.ai = true
vim.o.si = true 
vim.opt.nu = true
vim.wo.wrap = false
vim.opt.smartcase = true
vim.opt.incsearch = true
vim.opt.termguicolors = true
vim.opt.scrolloff = 8
vim.opt.modifiable = true
-- vim.opt.clipboard+=unnamedplus
vim.wo.fillchars = "eob: "
vim.opt.cmdheight = 1
vim.opt.mouse=a
vim.o.cmdheight=0
