require('plugins.nvim-tree')
require('plugins.bufferline')
require('plugins.lualine')
require('plugins.telescope')
require('plugins.nvim-surround')
require('plugins.ls-config')
-- require('plugins.vim-fugitive')
require('plugins.lsp')
require('plugins.comment')
require('plugins.which-key')
require('plugins.floaterm')

